feat: event payload implementation
rudderlabs/rudder-sdk-swift pull request #8
Opened 2024-11-12 15:21 UTC by SKannaniOS

## Description
This PR includes the payload implementation for Track, Screen, and Group events.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Code refactor/optimization

## Implementation Details
Each event contains several common fields in addition to fields unique to that specific event type. This PR implements all the common fields for events. Additionally, it introduces the `RudderOptions` model to manage `integrations` and `customContext` values. The `RudderIdentifyOptions` model is also introduced and will be utilized in future event implementations.

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added the necessary documentation (if appropriate).
- [x] I have ensured that my code follows the project's code style.
- [x] I have checked for potential performance impacts and optimized if necessary.
- [x] I have checked the code for security issues.
- [ ] I have updated the changelog (if required).

## How to test?

To run the sample app, configure the necessary values such as the write key and data plane URL in the AnalyticsApp class. The data plane will receive the Track, Screen, and Group events.

Sample Track Event JSON:
```
{
    "anonymousId": "CC23B8E5-5D97-4225-9E5C-03DF5947F303",
    "channel": "mobile",
    "context": {
        "SK1": {
            "Key1": "Value1"
        },
        "SK2": [
            "value1",
            "value2"
        ],
        "SK3": "Value3",
        "SK4": 1234,
        "SK5": 5678.9,
        "SK6": true
    },
    "event": "Track at 2024-11-14 18:01:51 +0000",
    "integrations": {
        "All": true,
        "SDK": true,
        "Segment": false
    },
    "messageId": "40F9AA0A-33A6-4AAF-A08E-26692F532F56",
    "originalTimeStamp": "2024-11-14T18:01:51.700Z",
    "properties": {
        "key": "value"
    },
    "receivedAt": "2024-11-14T18:02:00.305Z",
    "request_ip": "106.51.148.64",
    "rudderId": "2836452c-f55b-40aa-aef2-b79476455727",
    "sentAt": "2024-11-14T18:01:58.144Z",
    "type": "track"
}
```

Sample Screen Event JSON:
```
{
    "anonymousId": "E30C3220-8ECC-4746-83B7-657F214975D7",
    "channel": "mobile",
    "context": {
        "SK": {
            "Key1": "Value1"
        }
    },
    "event": "Analytics Screen",
    "integrations": {
        "All": true,
        "Segment": false
    },
    "messageId": "458C7801-D471-4039-9CEF-E44D2013FE97",
    "originalTimeStamp": "2024-11-14T18:04:58.558Z",
    "properties": {
        "key": "value",
        "name": "Analytics Screen"
    },
    "receivedAt": "2024-11-14T18:05:09.035Z",
    "request_ip": "106.51.148.64",
    "rudderId": "d11cbd78-d252-4bf6-a29f-6eee75b74220",
    "sentAt": "2024-11-14T18:05:08.134Z",
    "type": "screen"
}
```

Sample Group Event JSON:
```
{
    "anonymousId": "4EC697F2-9BD2-4016-AD2C-7756E4C59CA3",
    "channel": "mobile",
    "context": {
        "SK": {
            "Key1": "Value1"
        }
    },
    "groupId": "group_id",
    "integrations": {
        "All": true,
        "MySDK": false
    },
    "messageId": "F1EB4361-CCDA-40A1-89D1-D098C9EE4F7E",
    "originalTimeStamp": "2024-11-14T18:05:36.376Z",
    "receivedAt": "2024-11-14T18:05:38.283Z",
    "request_ip": "106.51.148.64",
    "rudderId": "75bdfd20-2cd2-4d52-8b7b-88c0cf71660b",
    "sentAt": "2024-11-14T18:05:38.132Z",
    "traits": {
        "anonymousId": "4EC697F2-9BD2-4016-AD2C-7756E4C59CA3",
        "key": "value"
    },
    "type": "group"
}
```

2024-11-15 12:54 UTC, 1abhishekpandey requested changes

2024-11-15 12:54 UTC, 1abhishekpandey commented on AnalyticsApp/AnalyticsApp/ContentView.swift
> +                    .addIntegration("Segment", isEnabled: false)
Please replace it with real values like `Amplitude` or `CleverTap`.
```suggestion
                    .addIntegration("Amplitude", isEnabled: true)
                    .addIntegration("CleverTap", isEnabled: false)
```

2024-11-15 12:54 UTC, 1abhishekpandey commented on AnalyticsApp/AnalyticsApp/ContentView.swift
> +                    .addIntegration("Segment", isEnabled: false)
Update these keys as well.

2024-11-15 12:54 UTC, 1abhishekpandey commented on AnalyticsApp/AnalyticsApp/ContentView.swift
> +                        .addIntegration("MySDK", isEnabled: false)
Update this key as well.

2024-11-15 12:54 UTC, 1abhishekpandey commented on Analytics/Analytics/Events/Message.swift
Let's add documentation for all the events i.e., track, screen and group.

Also, consider moving them into a separate class, under some event directory, if seems correct.

2024-11-15 12:54 UTC, 1abhishekpandey commented on Analytics/Analytics/Events/MessageOptions.swift
> +    }
Let's remove this method. As this is part of the identify event (not the current set of events). Let's not add anything, which is not part of the current scope.

2024-11-15 12:54 UTC, 1abhishekpandey commented on Analytics/Analytics/Events/MessageOptions.swift
> +    }
Remove all the instances of externalIds.

2024-11-15 12:54 UTC, 1abhishekpandey commented on Analytics/Analytics/Events/MessageOptions.swift
> +public class RudderIdentifyOptions: RudderIdentifyOptionType {
Please remove identify event-related code.

2024-11-15 12:54 UTC, 1abhishekpandey commented on Analytics/AnalyticsTests/MessageModuleTests.swift
> +final class MessageModuleTests: XCTestCase {
Let's refactor the test classes to follow the Android way to construct and match the exact JSON payload, refer [here](https://github.com/rudderlabs/kotlin-sdk-poc/blob/16e87407d4ef81cc077a385997ad340f2c058787/core/src/test/kotlin/com/rudderstack/kotlin/sdk/internals/models/TrackEventTest.kt#L40) for test class, and [here](https://github.com/rudderlabs/kotlin-sdk-poc/tree/16e87407d4ef81cc077a385997ad340f2c058787/core/src/test/resources/message/track) for the payloads.

2024-11-15 12:54 UTC, 1abhishekpandey commented on Analytics/AnalyticsTests/MessageModuleTests.swift
> +    func test_screen_event() {
Let's have a separate test class for the screen event.

2024-11-15 12:54 UTC, 1abhishekpandey commented on Analytics/AnalyticsTests/MessageModuleTests.swift
> +    // MARK: - Group
Let's have a separate test class for the group event.

2024-11-15 12:54 UTC, 1abhishekpandey commented on Analytics/AnalyticsTests/MessageModuleTests.swift
> +final class MessageModuleTests: XCTestCase {
Let's rename this class to be of type track.

2024-11-15 12:54 UTC, 1abhishekpandey commented on Analytics/AnalyticsTests/MessageModuleTests.swift
> +    // MARK: - Screen
We also need to test the category. Please write a unit test for that.

2024-11-15 18:18 UTC, SKannaniOS commented on Analytics/Analytics/Events/Message.swift
I have added basic documentation for the event models. There’s no need to create separate classes for each event at this stage. If the model size exceeds a certain limit, separate classes will be introduced in a future PR.

2024-11-18 09:26 UTC, SKannaniOS commented on Analytics/AnalyticsTests/MessageModuleTests.swift
> +final class MessageModuleTests: XCTestCase {
Event test cases will be refactored as a next PR.
FYR: https://linear.app/rudderstack/issue/SDK-2662/[ios]-refactor-tests-in-event-prs

2024-11-18 14:08 UTC, SKannaniOS commented on Analytics/AnalyticsTests/MessageModuleTests.swift
> +    // MARK: - Screen
Analytics tests will cover this scenario. But anyway, event test cases refactor PR will cover this again.

FYR: [https://linear.app/rudderstack/issue/SDK-2662/[ios]-refactor-tests-in-event-prs](https://linear.app/rudderstack/issue/SDK-2662/%5Bios%5D-refactor-tests-in-event-prs)

2024-11-18 14:10 UTC, SKannaniOS commented on Analytics/AnalyticsTests/MessageModuleTests.swift
> +final class MessageModuleTests: XCTestCase {
Event test cases will be refactored to have each event in its own class file. However, this won’t be implemented in the near future.

2024-11-18 14:11 UTC, SKannaniOS commented on Analytics/AnalyticsTests/MessageModuleTests.swift
> +    // MARK: - Group
Event test cases will be refactored in the next PR, with each event placed in a separate class file.

2024-11-18 14:11 UTC, SKannaniOS commented on Analytics/AnalyticsTests/MessageModuleTests.swift
> +    func test_screen_event() {
Event test cases will be refactored in the next PR, with each event placed in a separate class file.

2024-11-19 08:40 UTC, 1abhishekpandey approved these changes

2024-11-21 07:14 UTC, 1abhishekpandey approved these changes

2024-11-21 08:57 UTC, ChryssaAliferi approved these changes
🚀 Amazing! Let's gooo!

2024-11-21 15:26 UTC, merged